""" import streamlit as st
import os
import numpy as np
# Note: we updated the imports to match the new consolidated functions
from src.api_utils import LOCATIONS, get_live_data, get_historical_aqi
from src.model_utils import load_all_assets, run_predictions, create_gauge

# --- 1. INITIALIZE SESSION STATE ---
if 'aqi_data' not in st.session_state:
    st.session_state['aqi_data'] = [100.0, 100.0, 100.0]
if 'live_weather' not in st.session_state:
    st.session_state['live_weather'] = None

# --- 2. ASSET LOADING ---
rf_model, lstm_model, scaler = load_all_assets()

# --- 3. PAGE SETUP ---
st.set_page_config(page_title="Mumbai AQI Predictor", layout="wide")
st.title("🌬️ Mumbai Real-Time AQI Predictor")
st.markdown("Using Unified OpenWeather Telemetry")
st.markdown("---")

# --- 4. SIDEBAR: LOCATION & HISTORY ---
st.sidebar.header("📍 Location Settings")
# Dropdown to select the area in Mumbai
selected_location = st.sidebar.selectbox("Select Station Area", list(LOCATIONS.keys()))
coords = LOCATIONS[selected_location]

st.sidebar.divider()
st.sidebar.header("⏳ Historical Data")
if st.sidebar.button("Fetch Last 3 Days History"):
    with st.sidebar:
        with st.spinner(f"Accessing history for {selected_location}..."):
            # Pass the coordinates of the selected location
            st.session_state['aqi_data'] = get_historical_aqi(coords['lat'], coords['lon'])
            st.success("History Updated!")

st.sidebar.divider()
st.sidebar.subheader("Adjust Feature Inputs")
# These now default to the fetched historical values
day_3 = st.sidebar.number_input("AQI 3 Days Ago", value=float(st.session_state['aqi_data'][0]))
day_2 = st.sidebar.number_input("AQI 2 Days Ago", value=float(st.session_state['aqi_data'][1]))
day_1 = st.sidebar.number_input("Today's AQI", value=float(st.session_state['aqi_data'][2]))

# --- 5. MAIN DASHBOARD (REAL-TIME DATA) ---
if st.button(f"Refresh Live Data for {selected_location}", type="secondary"):
    with st.spinner(f"Connecting to OpenWeather sensors in {selected_location}..."):
        data = get_live_data(coords['lat'], coords['lon'])
        if data:
            data['station'] = selected_location
            st.session_state['live_weather'] = data
            st.session_state['aqi_data'][2] = float(data["aqi"])
            st.rerun()

# This is where your error was:
if st.session_state['live_weather']:
    w = st.session_state['live_weather'] # <--- These must be indented!
    st.info(f"📍 Station: {w['station']} | Condition: {w['desc']}")
    
    # Atmospheric metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Current AQI", w["aqi"])
    c2.metric("Temp", f"{w['temp']}°C")
    c3.metric("Humidity", f"{w['humidity']}%")
    c4.metric("PM 2.5", f"{w['pm25']} μg/m³")

    # MILESTONE 4: Extended Pollutant Dashboard
    st.markdown("### 🧪 Chemical Breakdown (μg/m³)")
    p1, p2, p3, p4, p5 = st.columns(5)
    p1.metric("PM10", w['pm10'])
    p2.metric("NO2", w['no2'])
    p3.metric("SO2", w['so2'])
    p4.metric("CO", w['co'])
    p5.metric("O3", w['o3'])

# --- 6. PREDICTION LOGIC ---
st.divider()
if st.button("Predict Tomorrow's AQI", type="primary"):
    # Run the inputs through the scaled model pipeline
    rf_final, lstm_final = run_predictions(day_3, day_2, day_1, rf_model, lstm_model, scaler)
    
    # Gauge Chart
    st.plotly_chart(create_gauge(rf_final), use_container_width=True)
    
    # Model Comparison
    col_a, col_b = st.columns(2)
    col_a.metric("Random Forest Prediction", f"{rf_final:.2f}")
    col_b.metric("LSTM (Neural Network)", f"{lstm_final:.2f}")
    
    # Health Advice Logic
    st.divider()
    if rf_final < 50:
        st.success("Health Advice: Air quality is Excellent. Perfect for outdoor exercise!")
    elif rf_final < 100:
        st.info("Health Advice: Air quality is Satisfactory. No precautions needed.")
    elif rf_final < 150:
        st.warning("Health Advice: Moderate. Sensitive groups should wear masks outdoors.")
    else:
        st.error("Health Advice: Poor Air Quality. Avoid prolonged outdoor exposure.")

# --- 7. HISTORICAL CONTEXT ---
st.divider()
st.subheader("Model Performance Analysis")
if os.path.exists("comparison_line.png"):
    st.image("comparison_line.png", caption="Historical Accuracy: Random Forest vs. LSTM")
else:
    st.info("Performance comparison chart will be displayed here once generated by the training notebook.") """

import streamlit as st
import os
import numpy as np
import pandas as pd # Added for the forecast table/chart
from src.api_utils import LOCATIONS, get_live_data, get_historical_aqi
from src.model_utils import load_all_assets, run_predictions, create_gauge, predict_7_days
from src.database_utils import init_db, log_aqi_data

# --- 1. INITIALIZE SESSION STATE ---
if 'aqi_data' not in st.session_state:
    st.session_state['aqi_data'] = [100.0, 100.0, 100.0]
if 'live_weather' not in st.session_state:
    st.session_state['live_weather'] = None

# --- 2. ASSET LOADING ---
rf_model, lstm_model, scaler = load_all_assets()

# --- 3. PAGE SETUP ---
st.set_page_config(page_title="Mumbai AQI Predictor", layout="wide")
st.title("🌬️ Mumbai Real-Time AQI Predictor")
# Initialize the database on startup
init_db()
st.markdown("---")

# --- 4. SIDEBAR: LOCATION & HISTORY ---
st.sidebar.header("📍 Location Settings")
selected_location = st.sidebar.selectbox("Select Station Area", list(LOCATIONS.keys()))
coords = LOCATIONS[selected_location]

if st.sidebar.button("Fetch Last 3 Days History"):
    with st.sidebar:
        with st.spinner(f"Accessing history for {selected_location}..."):
            st.session_state['aqi_data'] = get_historical_aqi(coords['lat'], coords['lon'])
            st.success("History Updated!")

st.sidebar.divider()
st.sidebar.subheader("Adjust Feature Inputs")
day_3 = st.sidebar.number_input("AQI 3 Days Ago", value=float(st.session_state['aqi_data'][0]))
day_2 = st.sidebar.number_input("AQI 2 Days Ago", value=float(st.session_state['aqi_data'][1]))
day_1 = st.sidebar.number_input("Today's AQI", value=float(st.session_state['aqi_data'][2]))

# --- 5. MAIN DASHBOARD (REAL-TIME DATA) ---
if st.button(f"Refresh Live Data for {selected_location}", type="secondary"):
    with st.spinner(f"Connecting to OpenWeather sensors in {selected_location}..."):
        data = get_live_data(coords['lat'], coords['lon'])
        if data:
            data['station'] = selected_location
            st.session_state['live_weather'] = data
            st.session_state['aqi_data'][2] = float(data["aqi"])
            
            # Database logging
            log_aqi_data(selected_location, data['aqi'], data['temp'], data['humidity'], data['pm25'])
            
            st.success("Data Logged to SQLite!")
            st.rerun()
            
if st.session_state['live_weather']:
    w = st.session_state['live_weather']
    st.info(f"📍 Station: {w['station']} | Condition: {w['desc']}")
    
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Current AQI", w["aqi"])
    c2.metric("Temp", f"{w['temp']}°C")
    c3.metric("Humidity", f"{w['humidity']}%")
    c4.metric("PM 2.5", f"{w['pm25']} μg/m³")

    st.markdown("### 🧪 Chemical Breakdown (μg/m³)")
    p1, p2, p3, p4, p5 = st.columns(5)
    p1.metric("PM10", w['pm10'])
    p2.metric("NO2", w['no2'])
    p3.metric("SO2", w['so2'])
    p4.metric("CO", w['co'])
    p5.metric("O3", w['o3'])

# --- 6. PREDICTION & 7-DAY FORECAST LOGIC ---
st.divider()
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("🔮 Tomorrow's Prediction")
    if st.button("Predict Tomorrow", type="primary"):
        rf_final, lstm_final = run_predictions(day_3, day_2, day_1, rf_model, lstm_model, scaler)
        st.plotly_chart(create_gauge(rf_final), use_container_width=True)
        
        # Health Advice
        if rf_final < 100:
            st.success(f"Target AQI: {rf_final:.2f} - Satisfactory")
        else:
            st.warning(f"Target AQI: {rf_final:.2f} - High Pollution")

with col_right:
    st.subheader("📅 7-Day Weekly Trend")
    if st.button("Generate Weekly Forecast"):
        with st.spinner("Calculating temporal patterns..."):
            # Call your predict_7_days function
            forecast_values = predict_7_days(day_3, day_2, day_1, rf_model, scaler)
            
            # Use the datetime fix from before
            import datetime
            tomorrow = datetime.date.today() + datetime.timedelta(days=1)
            dates = pd.date_range(start=tomorrow, periods=7).strftime('%b %d')
            
            # --- MAKE SURE THESE 3 LINES ALIGN WITH 'dates' ABOVE ---
            df_forecast = pd.DataFrame({"Date": dates, "Predicted AQI": forecast_values})
            st.line_chart(df_forecast.set_index("Date"))
            st.dataframe(df_forecast.T, use_container_width=True)
